### ISSUE TITLE
Measurement: Next Steps?

### ISSUE THREAD

**Issue by lmcairns-mphys** [r-preston/MPhysProject2021#14]
@mvesteri 
Hi Mika, just wondering what the next steps are for the measurement section?
Additionally wondering if you have any suggestions for background reading?

Thank you, hope you're well

**Comment by mvesteri** [comment]
Hi @lmcairns, 
For the measurement I suggest that the next step is to try and include your new plots in a latex document. I'll post some suggestions on how to do this in a moment. Then we should move onto the efficiency corrections and cross section determination.

I'll make a separate issue on the background material in a moment.

**Comment by mvesteri** [comment]
@lmcairns I think what you want to do is set up a chain so that you could checkout the repository from scratch and do
```bash
mkdir plots/ 
./run ./scripts/your_plotting_script.py # and tell this script to write to plots/
cd doc/measurement-doc/
pdflatex latex_source #and the latex knows to look in ../../plots/ to find the figures
# download/view the nice pdf document with lots of plots.
```
You should be able to delete the contents of `plots/` and quickly reproduce what you did.

Later we could define a generic `plot_directory` that could live anywhere in the warwick filesystem.

**Comment by mvesteri** [comment]
@lmcairns once we have this workflow set up then it should start to become very efficient to add more studies and plots. Something like `scripts/run_measurement.sh`
```bash
./scripts/your_data_mc_plotting.py
./scripts/your_efficiency_plotting.py
./scripts/your_cross_section_calculation.ph
# etc...
# all writing plots/tables etc.. to plots/
```

Then update the latex source so that it includes any new figures that you are developing...

```bash
source scripts/run_measurement.sh
cds doc/measurement-doc/
pdflatex ...
```

**Comment by lmcairns-mphys** [comment]
So I'm working through this, I've made plots/ and have my code writing to it, and I moved my code to scripts/ instead of src/. I'm trying to follow the command from your first reply:
`./run ./scripts/your_plotting_script.py` 
where my script is "mnt_setup_fnc.cpp" (I'll rename this soon to be more descriptive).

Firstly, what does ./run do? When I try this command I get a response:
`bash: ./run: No such file or directory`

Secondly, since I have to run mnt_setup_fnc.exe instead of .cpp, how would I tell the Makefile to write the .exe to the scripts/ directory instead of the top directory?

**Comment by mvesteri** [comment]
Hi @lmcairns sorry ignore the `./run` - that is something that we have in other frameworks to wrap the script in a special environment. I'm too used to writing `./run` 🤦 

And sorry just replace `./scripts/blah` with `mnt_setup_fnc.exe`.

**Comment by lmcairns-mphys** [comment]
@mvesteri 
In terms of the latex document, is there a way to include all the figures in plots without having to individually input their filenames to latex? To just automatically include all figures in plots?

I guess the main question is are we intending to automate the latex document, or will we need to manually need to input filenames, captions etc each time?

Additionally, are there any other features I should be adding to the latex document? Additional text or figure captions etc?

**Comment by mvesteri** [comment]
@lmcairns I would start by just putting their names by hand with (something like) `\includegraphics[\width=...]{../../plots/filename.pdf}`
I wouldn't worry too much about other text or captions for now. Just put the figures into the document.

Later I can suggest some tips for automatically including figures, but not worth doing right now.

**Comment by lmcairns-mphys** [comment]
@mvesteri 
Hi Mika,
Now that the Latex setup has been completed (see #16), what are the next steps for the measurement?

**Comment by mvesteri** [comment]
The next steps are 
* Determine the luminosity
* Determine the efficiency.

I'd suggest to start by determining the luminosity, and then we can already estimate the cross section under the crude assumption that the efficiency is perfect.

I'd suggest to write a small python script like `scripts/get_luminosity.py`.

To get started, try:
```python
import ROOT
rfile = ROOT.TFile(path_to_root_file)
lumi_tuple = rfile.Get('GetIntegratedLuminosityLumiTuple')
for entry in lumi_tuple:
     print(entry)
```

**Comment by lmcairns-mphys** [comment]
@mvesteri 
I've written this code, but I get an error when I run it:
`for entry in lumi_tuple:`
`TypeError: 'TObject' object is not iterable`
I've had a look for a solution but I'm struggling to find one, sorry.

**Comment by mvesteri** [comment]
I think that means that `rfile.Get...` didn't actually find the right object.

Ah now I see. The path should be `'GetIntegratedLuminosity/LumiTuple'`. I forgot the forward slash 🤦  -sorry

**Comment by mvesteri** [comment]
Note that you can write 
```python
rfile.ls()
```
to print the content of the file.

**Comment by lmcairns-mphys** [comment]
Ahh that makes sense now. Annoyingly I had used ls() to look at the file contents, but hadn't noticed the slash either. 

It's now giving an output, but each print operation is outputting:
`<ROOT.TTree object ("LumiTuple") at 0x54f5e70>`
for each entry instead of a value. Is this the intended output?

**Comment by mvesteri** [comment]
Ah maybe that doesn't work. Try instead 
```python
print(entry.IntegratedLuminosity)
```

**Comment by lmcairns-mphys** [comment]
I think I've fixed it now, I'm using:
`print(entry.IntegratedLuminosity)`
instead to output values.

So that's the script made, what's the next step?

**Comment by mvesteri** [comment]
And you should see a list of values printed. Some explanation on this:

I produced this file by running around 20 jobs on the grid, with each job processing a fraction of the data and making a file with the same content as what you see.
Afterwards I merged all of these files.
The number of entries in this luminosity tree corresponds to the number of files that I merged.
Each value is the luminosity of the data processed by that grid job.

So you just need to sum up these values and you get the total luminosity for this dataset.

The units are [inverse] picobarns.

So you could now try measuring the cross section for some kinematic cuts.
E.g. count the number of Z events in data where you have
* 60 < M < 120 GeV
* Both muons have pT > 20 GeV
* Both muons have 2 < eta < 4.5

And then divide by the luminosity to get the cross section in picobarns.

**Comment by lmcairns-mphys** [comment]
I had assumed the other branch of the tree is the error on the luminosity measurement, but when I print `entry.IntegratedLuminosityErr` it gives me the same value as for IntegratedLuminosity. Am I incorrect in my assumption that this is the error? Is the unit different?

**Comment by mvesteri** [comment]
It *would* be the uncertainty in the same units but unfortunately the luminosity isn't yet calibrated for this dataset. I think for now you could just assume that it has a relative uncertainty of 5%.

**Comment by mvesteri** [comment]
Note that the determination of the luminosity is one of the most difficult analyses in LHCb. See e.g. [this paper](https://arxiv.org/abs/1410.0149).

**Comment by lmcairns-mphys** [comment]
Total Luminosity found to be 64.6069543633 pb<sup>-1</sup>.
With 5% error this gives: 65±3 pb<sup>-1</sup>

Using the full value with 5% error, this gives cross sections (xsec) as:
![Screenshot 2020-11-16 185203](https://user-images.githubusercontent.com/72559837/99295067-d9134680-283c-11eb-812e-826ff1ae7890.png)

**Comment by mvesteri** [comment]
👍 but I mean't to apply *all* of those cuts. See e.g. that they are the same cuts used in the [13TeV LHCb Z cross section publication](https://arxiv.org/abs/1607.06495).

**Comment by lmcairns-mphys** [comment]
Ahh yes, that makes sense, oops 😅
Using all cuts together, that's:
- 3748 counts
- Cross section = 58±3 pb

**Comment by mvesteri** [comment]
👍 @lmcairns if you didn't already do so can you make a merge request to add this cross section script?
And I'd suggest to add it to a top-level script that runs this and your last plotting script. E.g. like
`scripts/run_xsec_analysis.sh` contains (just guessing the names of the scripts):
```bash
./scripts/plot_data_mc.py
./scripts/measure_cross_section.py
```

Then
```bash
source scripts/run_xsec_analysis.sh
```

Then we should move onto the efficiency determination.
