### ISSUE TITLE
Getting the cross section from Pythia

### ISSUE THREAD

**Issue by mvesteri** [r-preston/MPhysProject2021#17]
@r-preston we should try to get the cross section prediction from pythia.

You can ask for the `sigmaGen` method. See  [EventInformation](http://home.thep.lu.se/~torbjorn/pythia81html/EventInformation.html).

That will correspond to whatever cuts you asked pythia to make, which isn't very flexible.

You would want to be able to re-compute the cross section with different cuts.

So you can work out a scaling factor, which is equivalent to the luminosity of your `TTree`.

If you say `weight = pythia_sigmaGen/pythia_n_generated` then you can just do the sum of these weights from your `TTree` with any cuts and that will be the cross section. Not sure off the top of my head what units pythia uses but that will be in the documentation. Suggest that picobarns is a good natural unit for the Z cross section.

Hope that makes sense?

@lmcairns is in the process of trying to estimate the cross section from the real data so you should be able to compare with that.
I suggested comparing the cross section for 
* 60 < M < 120 GeV
* Both muons with pT > 20 GeV
* Both muons with 2 < eta < 4.5

**Comment by r-preston** [comment]
@mvesteri I'm somewhat recovered and have been giving this a go. I'm a little confused about what `pythia_n_generated ` stands for. The documentation isn't super clear but I think `sigmaGen()` gives the cross section for each event, so it makes sense that the muon pair for a given event will have this value associated with it multiplied by some factor. I've tried dividing by the number of particles per event (`event.size()`) but this gives a cross section about 2 orders of magnitude too big

**Comment by mvesteri** [comment]
Great to hear that you're feeling better @r-preston 

I'm pretty sure that `sigmaGen()` just gives the cross section, which is independent of the number of events that you generate. 

What value does that give?

**Comment by r-preston** [comment]
@mvesteri I had assumed it was per event as the value changed for every call to `pythia.next`. The value was usually around 78,000pb

**Comment by mvesteri** [comment]
I think it changes because it is being integrated. So as you generate more events the cross section gets more numerically precise.
