### ISSUE TITLE
Modelling the QCD background in the W data sample

### ISSUE THREAD

**Issue by mvesteri** [r-preston/MPhysProject2021#28]
@lmcairns 

The background is mostly from charged pions and kaons decaying to muonic final states. You could look up the branching fractions of these decays from the "PDG live" webpage.

What we need is a "shape" of this background that we could float in a fit of the W->munu candidate sample.

You see below that there are several paths in the data files. 
I suggest to look at the `W{m,p}SingleTrackNoBias/DecayTree` path which contains a selection of high pT tracks **without** any muon identification requirement. These will be mostly [charged] pions and kaons.

Steps (just pick one charge to start with, e.g. Wp):
* Plot the muon pT distribution and see how the shape looks.
* Try to fit the distribution with different shapes. Skeleton python code below. The exponential function probably won't work very well, but try that first and then I can suggest how to use a generic functional form.
* ...
* Eventually we'll have a well understood background shape/function and we can use it to create a histogram template that you can use in a fit of the W data candidates.

```python
hist = ROOT.TH1F('hist','Track transverse momentum',100,15.,60.)
tree.Draw('mu_PT*1.e-3>>hist')
hist.Fit('expo') # fit with an exponential function.
c = ROOT.TCanvas()
hist.Draw()
c.Print('plot.png')
```

```
./run root -l /storage/epp2/phshgg/DVTuples__v23b/5TeV_2017_32_Down_EW.root 
root [0] 
Attaching file /storage/epp2/phshgg/DVTuples__v23b/5TeV_2017_32_Down_EW.root as _file0...
(TFile *) 0x371c140
root [1] gDirectory->ls()
TFile**		/storage/epp2/phshgg/DVTuples__v23b/5TeV_2017_32_Down_EW.root	
 TFile*		/storage/epp2/phshgg/DVTuples__v23b/5TeV_2017_32_Down_EW.root	
  KEY: TDirectoryFile	WpIso;1	WpIso
  KEY: TDirectoryFile	WmIso;1	WmIso
  KEY: TDirectoryFile	WpNoIso;1	WpNoIso
  KEY: TDirectoryFile	WmNoIso;1	WmNoIso
  KEY: TDirectoryFile	WmSingleTrackNoBias;1	WmSingleTrackNoBias
  KEY: TDirectoryFile	WpNoMuID;1	WpNoMuID
  KEY: TDirectoryFile	WpSingleTrackNoBias;1	WpSingleTrackNoBias
  KEY: TDirectoryFile	WmNoMuID;1	WmNoMuID
  KEY: TDirectoryFile	ZMuID;1	ZMuID
  KEY: TDirectoryFile	Z;1	Z
  KEY: TDirectoryFile	ZTrkEff;1	ZTrkEff
  KEY: TDirectoryFile	GetIntegratedLuminosity;1	GetIntegratedLuminosity
```

**Comment by lmcairns-mphys** [comment]
@mvesteri 

I've plotted a fit for expo in C++, and spent some time fiddling with it to get the fit to show in the legend and the stat box. See example for Wp below.
![W_back_plot_expo](https://user-images.githubusercontent.com/72559837/104776109-70c7df00-5771-11eb-970f-fb3ad680ab47.png)

I have uploaded my code as commits to Pull Request #26 (I wasn't aware that it was still open, I had intended to open new pull request, oops!)

**Comment by mvesteri** [comment]
Nice looking plot @lmcairns .  I'm wondering if we return to trying different fit functions later, and now move on to trying to make a histogram template out of your exponential function, so that we can try and fit the muon data.

You can do the following:
* Instead of doing `hist.Fit("expo")`, which only works for a few simple functions, you should make a `TF1` object.
* `function = ROOT.TF1("my_expo","[0]*TMath::Exp(-[1]*x)")`
* `hist.Fit("my_expo")`
* `background_template = ROOT.TH1F(... you can fill in the rest...`
* `for event in range(10000): background_template.Fill(function.GetRandom())`
* Alternatively you could fill the histogram deterministically by looping over the bins and doing `hist.SetBinContent(bin_number,function.Eval(hist.GetBinCenter(bin_number)`

**Comment by lmcairns-mphys** [comment]
@mvesteri 
I was just wondering what [0] and [1] represent in the line:
`function = ROOT.TF1("my_expo","[0]*TMath::Exp(-[1]*x)")`
How do I set these and what values should they take?

**Comment by mvesteri** [comment]
Hi @lmcairns, these represent the two `parameters` of the function.
You can set the parameters like 
```python
# e.g. set them both to 1.
function.SetParameter(0,1.)
function.SetParameter(1,1.)
```
And then you can fit the function to a histogram like
```python
my_histogram.Fit(function.GetName())
```
Note that the fitting is normally not happy if you don't set starting values for the parameters, though it may still work in simple cases like this (only two free parameters).

**Comment by lmcairns-mphys** [comment]
Hi @mvesteri,
I have added this to my code producing the fit (for [0]=[1]=1.0) and background templates in the figures below.
![W_expo_back_plot](https://user-images.githubusercontent.com/72559837/105070468-3dd86080-5a7b-11eb-86d0-303f9c991749.png)
![W_background_template](https://user-images.githubusercontent.com/72559837/105070472-3fa22400-5a7b-11eb-9f51-1d4d9371de1b.png)

What would be the next step? I assume I would have to edit the W isolated signal code to remove this background?

**Comment by mvesteri** [comment]
👍 @lmcairns . As a next step you could try to "fit" the W isolated data with a sum of the signal simulation plus this background template. 
* Create a signal fraction variable.
* The [redundant] background fraction is [1 - signal_fraction].
* Scale both signal and background histograms by the factor `data_integral*fraction/histogram_integral`. 
* Then you can create a sum (or fit model) histogram and compare it to the data.

Does that make sense? Hopefully that is a very quick exercise. 

Then we can get you set up with the `TFractionFitter` tool to automatically fit the fraction.

**Comment by lmcairns-mphys** [comment]
@mvesteri I feel like this might be a stupid question, but how do I determine the signal fraction variable? I'm unsure how to produce a numerical value for this from two histograms.

**Comment by mvesteri** [comment]
In this first exercise you have to guess/estimate it by eye initially. And then tweak the value until your signal+background sum better describes the data. 
E.g. start by guessing that the isolated W sample is 50% signal and 50% background.
Then just use the `Scale` and `Add`  functions of the ROOT histogram class to make your sum histogram.

**Comment by mvesteri** [comment]
I probably should have said that you should plot the muon pT distribution from the "isolated" data with some minimal isolation cut. E.g. require that the isolation is < 3 GeV. And start the plot from pT > 20 GeV. Otherwise the sample will be totally background dominated.

**Comment by lmcairns-mphys** [comment]
Ahh okay that makes sense. I had the rest, was just a bit unsure of the fraction.

Will add those cuts now!

**Comment by lmcairns-mphys** [comment]
One plot with cuts:
![W_fit_model](https://user-images.githubusercontent.com/72559837/105094122-b2bb9280-5a9b-11eb-9e6f-4c4fbcaa1a42.png)

**Comment by mvesteri** [comment]
Ok, but that is a plot of the isolated muon data? (The legend suggests that it is a fit "model", i.e. some combination of data/simulation templates)

If, as I suspect, this is the isolated muon data then you can go ahead and try and model this with a sum of signal and background templates. You just have to find a signal fraction that roughly describes the data. No point doing this too carefully, since we can quickly move on to using a fitting/minimisation tool.
