### ISSUE TITLE
Fig10 Value Differences

### ISSUE THREAD

**Issue by lmcairns-mphys** [r-preston/MPhysProject2021#33]
Hi @mvesteri 

I checked the 8 TeV 2015 paper (https://arxiv.org/abs/1511.08039) again to get their sources, and found that the 7 TeV Z paper in 2015 (https://arxiv.org/abs/1505.07024) had updated values of the W xsecs using more precise efficiency values, so that explains the biggest discrepancy in the values in Fig10 vs the papers. However the differences in the errors use still remain, and there are two small differences in the exact values used, in the 7 TeV Wp xsec and the 8 TeV Wm xsec. I have highlighted these differences in bold. See the comparison below:

|                  | Fig10.C                | Values quoted in Papers |
|------|------|------|
| 7 TeV, W+ | **878.4 ± 16.6** | **878.0 ± 33.1** |
| 7 TeV, W-  | 689.5 ± 13.1       | 689.5 ± 25.4 |
| 7 TeV, Z     | 76.0 ± 1.3           | 76.0 ± 3.1 |
| 8 TeV, W+ | 1093.6 ± 18.3     | 1093.6 ± 32.9 |
| 8 TeV, W-  | **819.4 ± 13.0** | **818.4 ± 23.4** | 
| 8 TeV, Z     | 95.0 ± 1.7           | 95.0 ± 3.2 |

Checking the break down of the errors, it doesn't appear that one of the separated errors has been removed from the errors used in Fig10.C (ie. subtracting luminosity), but I may be wrong on this.

**Comment by mvesteri** [comment]
Just picking the last row of your table, the abstrac of https://arxiv.org/abs/1511.08039
has an uncertainty of `math.sqrt(0.3**2 + 0.7**2 + 1.1**2 + 1.1**2) = 1.7320508075688772`, which appears to be consistent with your `Fig10.C` column?

**Comment by lmcairns-mphys** [comment]
Ahh. Well it appears I have done my error propagation incorrectly again. I'll correct that now.
