### ISSUE TITLE
W xsec improvement: Track Cut

### ISSUE THREAD

**Issue by lmcairns-mphys** [r-preston/MPhysProject2021#35]
@mvesteri 
I have done the initial steps of the track cut analysis, but have not yet calculated the new systematic errors it introduces. See analysis report using both the eta cuts and the track chi squared/ndf cut: [measurement_report.pdf](https://github.com/r-preston/MPhysProject2021/files/6070669/measurement_report.pdf)

The track cut has a clear improvement on the fitting of the K/pi background, as seen in the plots for Wm below, but as the slope is  lower than the value I previously manually set the slope to be (0.2), the overall fit model is not as accurate to the data as it used to be; the chi2/ndf is roughly doubled. See the comparison for Wm below; Wm shows the difference more clearly, whilst I think the Wp analysis suffers more from the limited statistics of the W signal simulation.

Wm, only eta cut:
![W-_expo_back_plot_only_eta](https://user-images.githubusercontent.com/72559837/109691595-80638180-7b7f-11eb-9a37-58f383594eac.png)
Wm, both eta and track cuts:
![W-_expo_back_plot_both](https://user-images.githubusercontent.com/72559837/109691589-80638180-7b7f-11eb-9276-0edd4a8e4d28.png)
Wm fit model with manually fixed slope (0.2):
![W-_fit_model_0 2](https://user-images.githubusercontent.com/72559837/109696279-ca9b3180-7b84-11eb-8c54-c59a7c56a329.png)
Wm fit model with track cut slope, not fixed:
![W-_fit_model](https://user-images.githubusercontent.com/72559837/109696275-ca029b00-7b84-11eb-9398-e8653f9b4bf5.png)

The cross sections produced using this cut are reduced compared to fixing the slope, which although brings them closer to the expected theoretical values, it does mean that the 3 cross sections no longer differ from the theory
by roughly the same factor, so some error may originate in places other than the luminosity.

I had a few questions about how to proceed, as I have some issues:
1. I'm unsure what values I should be comparing in order to determine the systematic error introduced by this change: should I compare the cross section outputs, or the W signal fractions used to determine the cross sections? 
2. Furthermore, should I use the manual setting of the background slope in this comparison? I obviously won't use it in the value produced with this track cut, but I have had some errors when trying to perform the fraction fitting on Wp for the value without the track cut. If I do not manually set the slope of the Wp background fit (with only the eta cut), TFractionFitter does not run and a value is not produced. The error that occurs is `abnormal termination of minimization`, which can be fixed by using an initial value closer to the expected outcome, but I can't change this when using the slope from the fit without manually resetting it. I am unsure of the best way to fix this.
3. Is error on the signal fraction systematic? I've currently included it in the statistical error, as the signal fraction is used in calculation of number of W events for the xsec calculation, but I'm thinking this may not be correct?

(As an additional update, I have fixed the error propagation issues I referenced in #33, and have made progress with the comparison plots, although I am having some small issues with TMultiGraph that are slowing me down somewhat.)

**Comment by mvesteri** [comment]
👍 @lmcairns 
Can I suggest restricting the fit range for your exponential fit to, e.g., < 30 GeV? I think you will get a steeper fit in that case.
To answer your questions

1. It is up to you how to handle the systematic uncertainty. You could treat this as a systematic uncertainty on the signal fraction and just propagate that through your cross section calculation. Or you could just look how much the cross section changes. I think this is just a question of what is more convenient in the code. The answer will be the same I think. This systematic uncertainty should propagate to the W+ and W- cross sections, the W+/W- ratio and the W/Z ratio.
2. I suspect that you'll get a much better fit if you use extract/fit the background function in the range 15 < pT < 30 GeV. Maybe try this first?
3. The `TFractionFit` uncertainties are definitely of the statistical type. The systematic uncertainties will be from discrete variations in the fit method, selection cuts, etc..
