### ISSUE TITLE
Efficiency measurement

### ISSUE THREAD

**Issue by r-preston** [r-preston/MPhysProject2021#42]
@mvesteri just wanted to check that `5TeV_2017_32_Down_EW.root` is the right root file?

**Comment by mvesteri** [comment]
Yes, but please could you take it from this directory now:
`/storage/epp2/phshgg/Public/DVTuples__v24f/5TeV_2017_32_Down_EW.root`

**Comment by r-preston** [comment]
@mvesteri I've written a script to [calculate the trigger efficiency](https://github.com/r-preston/MPhysProject2021/commit/48f95bf908917beab73a00e59d9b967c1a68399b), however the numbers aren't looking right. With or without the phase space cuts, each individual muon has an efficiency of ~90%, which works out to a roughly 99% overall trigger efficiency which seems to me to be much too high. 
The data is coming from the `Z/DecayTree` TBranch of `5TeV_2017_32_Down_EW.root`

**Comment by mvesteri** [comment]
I think the code looks OK. Maybe the efficiency is indeed 90%. To further understand this I would anyway suggest to move on to the next step, which is to plot the efficiency as a function of the muon pseudorapidity.

A shortcut to get this is to just fill three histograms of the muon eta, using the same conditions as you had before.

Then the efficiencies (as a function of pseudorapidity) are just ratios of these histograms.

(It is of course interesting to study the efficiency as a function of other variables but the pseudorapidity dependence is known to be quite strong)

**Comment by r-preston** [comment]
@mvesteri I've got a working script producing histograms but I'm a little confused about the bins - for the mu- and mu+ histograms it makes sense to use mum_ETA and mup_ETA respectively, but what is the bin variable for the 'both triggering' histogram?

**Comment by mvesteri** [comment]
I would suggest to consider mu+ and mu- as different species/particles for a moment.
So make a plot of the mu+ efficiency as a function of eta, and then an independent plot for the mu-.
Maybe that simplifies things?
And maybe it is also worthwhile to check that the efficiencies are independent of charge.
(Actually it is possible to get a different efficiency if there is a mis-alignment effect in the detector)

**Comment by r-preston** [comment]
@mvesteri I think that's what I'm currently doing, I've got two histograms of `mu[m/p]_L0MuonEWDecision_TOS` against the corresponding eta, which are looking resonable and are pretty much the same for both species bar some minor differences. 
I'm assuming that creating three histograms and taking the ratio is essentially recreating the trigger efficiency equation with histograms, but I don't know what eta or other variable to use for the denominator (both trigger-on-signal). 

I'm also trying to get my head around ROOT's `TRatioPlot` which seems ideal for this, however the formatting is proving very intractable. I would attach an image of the ratio of each species but I can't seem to attach images to these comments.

**Comment by mvesteri** [comment]
Example python implementation of what I mean:
```python
hist_template = ROOT.TH1D('template','',100,1.8,5.0)
hist_mup_numer = hist_template.Clone('mup_numer')
hist_mup_denom = hist_template.Clone('mup_denom')
tree.Draw('mup_eta>>mup_numer','mum_L0MuonEWDecision_TOS && mup_L0MuonEWDecision_TOS')
tree.Draw('mup_eta>>mup_denom','mum_L0MuonEWDecision_TOS')
hist_mup_eff = hist_template.Clone('mup_eff')
hist_mup_eff.Divide(hist_mup_numer,hist_mup_denom,1.0,1.0,"B") #note that the B gives "binomial" errors
c = ROOT.TCanvas()
hist_mup_eff.Draw()
c.SaveAs('eff.png')
```

Once you want to make the same plot for the mu- you'll probably want to use dictionaries/lists with a loop over the two muon charges so there is no code duplication.

**Comment by r-preston** [comment]
@mvesteri Thanks, I had eventually got something very similar to what you suggested, although the binomial errors flag helped a lot.
