### ISSUE TITLE
Splitting up the work

### ISSUE THREAD

**Issue by mvesteri** [r-preston/MPhysProject2021#5]
@r-preston @lmcairns now that we're getting more familiar with ROOT and the data formats I think it is time to start getting more seriously into the project of measuring W and Z cross sections for sqrts = 5 TeV pp collisions.
I think we should start by focussing on the Z cross section, which is more straightforward than the W because it is essentially background free. I think we should divide the work into two parts

1. The hypothesis, i.e. the theory prediction of the cross section.
2. The measured cross section.

Maybe I explain these in a bit more detail before you decide who wants to focus on which part.

**The hypothesis**
* See if you can download and install the `pythia` package, e.g. from [here](http://home.thep.lu.se/Pythia/).
* Pythia is a general purpose event generator for various types of collisions (e.g. proton-proton, electron-positron, proton-electron, etc...)
* It is a "leading order" (in the perturbation theory sense) generator which means that it has no quantum-loop corrections. 
* This means that it is not expected to give an accurate description of the total cross section. However it tends to give a good description of the *differential* cross section versus, e.g., the boson transverse momentum.
* Nevertheless `Pythia` is the most user friendly event generator so we should start there.
* As we progress we might try higher-order programs and see how the extra orders (primarily in the strong coupling constant) affect the predicitons.

**The measurement**
* The next step is to try to compare our data with simulated Z -> mumu decays.
* Essentially we need to make plots of various distributions of the muon (and di-muon) properties, overlaying the real data with simulation.
* The simulation samples can be found in the same directory.
* After that, the following step will be to try and correct our cross section measurement for the trigger efficiency. This will require trying to measure that efficiency directly from the data.

**General comments**
I suggest starting to populate a set of draft documents, which can be used as a basis of your formal reports, but should not have any constraint on length/content. These would eventually evolve into official LHCb "analysis notes", which would get reviewed and could become a real LHCb journal publication. I think it should then be quite straightforward to pick material out of these and edit them into your assessment reports.
Concretely, what I suggest is:
* Create a `doc/` directory in the repository with subdirectories like `doc/theory_predictions` and `doc/Z_xsec_measurement`.
* Then try to populate these subdirectories with `latex` source.
* We need to try and work towards automated/reproducible analysis workflows. Therefore I suggest to write a top-level script for each of the two new tasks, with the idea that these scripts produce all of the plots/tables/numbers that are needed for the two documents.

**Comment by mvesteri** [comment]
@r-preston @lmcairns for the measurement part I needed to mention that the simulated Z "data" events can be found in this path `/storage/epp2/phshgg/DVTuples__v23/13TeV_2016_28r1_Down_Z_Sim09h.root`. The events should look just like the data events but you may notice that there are additional branches/leaves in the `TTree`, related to "true" information about the generated decay. Obviously this "truth" information wouldn't be available in the "real" data.

**Comment by r-preston** [comment]
@mvesteri Me and Laura have decided that (at least initially) I'll be focusing on the hypothesis side and Laura will focus on the measurement side.
I've managed to successfully install Pythia and get it working for both C++ and Python, what is the next step?

**Comment by mvesteri** [comment]
@r-preston OK the next step is to try and generate some Z ->mumu events and fill a `ROOT` `TTree` with them.
You should be able to find some example for generating Z events in the `examples/` directory of pythia. For the `TTree` some skeleton C++ code
```cpp
#include <TFile>
#include <TTree>
#include "Pythia8/Pythia.h"
int main(){
Pythia8::Pythia pythia;
    pythia.readString( "WeakSingleBoson:ffbar2gmZ = on" );
    pythia.readString( "PhaseSpace:mHatMin = 60" );
    pythia.readString( "PhaseSpace:mHatMax = 120" );
    pythia.readString( "23:onMode = off" );
    pythia.readString( "23:onIfAny = 13" );//force Z to decay to muon (google "MC particle numbering scheme" to see where the 23 and 13 come from).
TFile output("pythia.root","RECREATE");
TTree tree("tree","tree");
float Z_mass;
tree.Branch("Z_mass",&Z_mass,"Z_mass/F");
int n_events = 1000;
for (int i_event = 0; i_event < n_events; ++i_event){
   if ( !pythia.next() ) {
      continue;
    }

     // try to get the Z mass from the pythia information
     //for ( auto i = 0; i < event.size(); ++i ) { 
     // try to inspect event[i], i.e. particle i in this event. ...
     //}
     Z_mass = Z_mass_from_pythia;
     tree.Fill();
}
output.Write();
output.Close()
}
```

There will also be plenty of examples to do the same in python.

**Comment by mvesteri** [comment]
@r-preston if you get stuck on this please do ask Miguel Ramos Pernas. He is an expert on this sort of thing.

**Comment by lmcairns-mphys** [comment]
@mvesteri Regarding working on the measurement section, which muon/di-muon properties would be most useful for me to focus on and start plotting tomorrow? How would these correspond to calculating the cross section? 

You mentioned in last weeks meeting possibly having separate meetings tomorrow to discuss the work required for each session more specifically. Is this still possible? I know you are unavailable for the Thursday meeting and I'm unsure if that extends to tomorrow as well? I'd find it very useful to go through what the measurement working requires in a bit more detail either way.

**Comment by mvesteri** [comment]
@lmcairns next week we can certainly start having separate meetings on the two threads of the analysis.

For the measurement I'd suggest to try and make plots of the data and simulation for the 
- muon pT, eta, phi
- dimuon mass, pT, rapidity (note the difference between rapidity and pseudorapidity(eta)).

Miguel should be happy to answer questions on how to make the plots.
